linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - varnamelen # Not relevant
    - lll # not relevant
    - exhaustruct # Not relevant
    - goerr113 # Too strict
    - gochecknoglobals
    - gochecknoinits # useless

linters-settings:
  misspell:
    locale: US
  funlen:
    lines: -1
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/tomMoulard/fail2ban
          - github.com/http-wasm/http-wasm-guest-tinygo
  godox:
    keywords:
      - FIXME
  revive:
    rules:
      - name: struct-tag
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        disabled: true
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
        disabled: true
      - name: unreachable-code
      - name: redefines-builtin-id
  testpackage:
    allow-packages:
      - fail2ban

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: '(.+)_test.go'
      linters:
        - funlen
    - path: 'fail2ban.go'
      text: 'calculated cyclomatic complexity for function shouldAllow is 12'
    - path: 'fail2ban.go'
      text: "Function 'ShouldAllow' has too many statements"
    - path: 'fail2ban_test.go' # false-positive
      text: 'response body must be closed'
    - path: 'fail2ban.wasm.go'
      text: 'func \`main\` is unused'
    - path: 'fail2ban.wasm.go'
      text: 'func \`\(\*Middleware\)\.handleRequest\` is unused'
    - path: 'fail2ban.wasm.go'
      linters:
        - nonamedreturns # for reqCtx in handleRequest
