project_name: fail2ban

builds:
  - binary: plugin.wasm
    gobinary: tinygo
    no_unique_dist_dir: true
    main: ./wasm/
    flags:
      - -scheduler=none
      - --no-debug
      - -target=wasi
      - -tags=WASM
    ldflags:
      - ''
    goos:
      - linux
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'

archives:
  - id: fail2ban
    name_template: '{{ .ProjectName }}_v{{ .Version }}'
    format: zip
    files:
      - LICENSE
      - .traefik.yml
