services:
  traefik:
    image: traefik:v3.3
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
      - --accesslog
      - --experimental.localPlugins.fail2ban-local.moduleName=github.com/tomMoulard/fail2ban
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/plugins-local/src/github.com/tomMoulard/fail2ban/
    tty: true

  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    command: >-
      -name whoami -verbose true
    labels:
      traefik.http.routers.fail2ban-local.rule: Host(`fail2ban-local.localhost`)
      traefik.http.routers.fail2ban-local.middlewares: fail2ban-local
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.enabled: true
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.bantime: 3h
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.findtime: 10m
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.maxretry: 4
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.statuscode: "400,401,403-499"
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.sourceCriterion.requestHeaderName: Cf-Connecting-Ip

