services:
  traefik:
    image: traefik:v3.2
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
      - --accesslog
      - --experimental.localPlugins.fail2ban.moduleName=github.com/tomMoulard/fail2ban
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=tech@les-vikings.fr
      - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - 42888:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/plugins-local/src/github.com/tomMoulard/fail2ban/
      - ./data:/data
    user: 'root:root'
    tty: true

  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    command: >-
      -name whoami -verbose true
    labels:
      traefik.http.routers.fail2ban.rule: Host(`traefik-test.drakkar.pro`)
      traefik.http.routers.fail2ban.entrypoints: websecure
      traefik.http.routers.fail2ban.middlewares: fail2ban
      traefik.http.routers.fail2ban.tls: true
      traefik.tls.stores.default.defaultgeneratedcert.resolver: myresolver
      traefik.tls.stores.default.defaultgeneratedcert.domain.main: traefik-test.drakkar.pro
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.enabled: 'true'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.bantime: '60s'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.findtime: '60s'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.maxretry: '1'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.allowlist.ip: '127.0.0.2'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.denylist.ip: '127.0.0.3'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.urlregexps[0].regexp: '/no'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.urlregexps[0].mode: 'block'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.urlregexps[1].regexp: '/yes'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.urlregexps[1].mode: 'allow'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.rules.statuscode: '400,401,403-499'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.cloudflare.enabled: 'true'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.cloudflare.apiToken: 'KTpsvWPFjAbB81jHDb26DGHutjw-INHl4TVh78EE'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.cloudflare.zoneId: '79462d5d2be0c4d252c5f9f087e571e4'
      traefik.http.middlewares.fail2ban.plugin.fail2ban.persistencePath: '/data/blocked-ips.json'
